config:
  # 程序的mongo地址
  MONGODB_URL: 'mongodb://192.168.0.48:38213'
  # 数据库的database
  MONGODB_DATABASE: 'MOOP'
  # 输出日志格式
  LOG_FORMAT: '%(asctime)s - %(filename)s:%(lineno)s - %(name)s:%(funcName)s - [%(levelname)s] %(message)s'